# Generated by Django 4.2.3 on 2023-07-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_lesson_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_link',
            field=models.URLField(default='', max_length=150, unique=True, verbose_name='ссылка на видео'),
        ),
    ]
