# Generated by Django 4.2.3 on 2023-08-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_lesson_lesson_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_link',
            field=models.URLField(default='lesson/<int:pk>/', max_length=150, unique=True, verbose_name='ссылка на видео'),
        ),
    ]
