# Generated by Django 4.2.3 on 2023-08-29 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_paynment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paynment',
            new_name='Payment',
        ),
    ]
