# Generated by Django 4.2.3 on 2023-08-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_paynment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_of_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
