# Generated by Django 4.2.3 on 2023-09-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_remove_payment_client_payment_is_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_payment',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activ', models.BooleanField(default=False, verbose_name='Подписка')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('well_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.well', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
