# Generated by Django 4.2.3 on 2023-09-02 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_payment_is_payment_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='is_activ',
            field=models.BooleanField(default=True, verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='well_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.well', verbose_name='курс подписки'),
        ),
    ]
